services:
  postgres:
    image: postgres:16
    container_name: ahcl-postgres
    environment:
      POSTGRES_USER: autohost
      POSTGRES_PASSWORD: autohost
      POSTGRES_DB: autohost
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./infrastructure/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autohost -d autohost"]
      interval: 5s
      timeout: 5s
      retries: 10

  # opcional: GUI
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: ahcl-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@local.test
      PGADMIN_DEFAULT_PASSWORD: devpass
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db_data:
